### ISSUE TITLE
Add .gitignore file

### ISSUE THREAD

**Issue by alexanderjervis** [2105-may24-devops/alex-project0#3]
To prevent the .pyc files in the pycache from being sent up and saved into github.

**Comment by Mewr11** [comment]
I'll be working on this issue, if that's okay with you.

**Comment by Mewr11** [comment]
Were there any files you wanted added to the .gitignore other than the python standard (https://github.com/github/gitignore/blob/master/Python.gitignore)?

**Comment by alexanderjervis** [comment]
I have no preference I just added this as an issue after he mentioned it yesterday and was waiting for him to explain it. So if you want to go ahead and create it, that's fine with me. I don't really have any idea what a .gitignore is or what it contains.

**Comment by Mewr11** [comment]
A .gitignore is just a list of files that git won't add when you call `git add .`; Frequently we use it to exclude compiled code, caches, unit test outputs, and so on.

**Comment by alexanderjervis** [comment]
Ok, yeah it should exclude the defaults as well as pycache and also AGcharacters, since I feel that each user should have characters different from the main branch, but the AGmodules should be inherited since they should be consistent across branches.
